FROM python:3.13-slim

WORKDIR /app

COPY . /app

RUN pip install --upgrade pip \
    && pip install uv mcp-proxy \
    && uv sync 

CMD ["mcp-proxy", "--port=8080", "--pass-environment", "--transport=streamablehttp", "--stateless", "--host=0.0.0.0", "--", "uv", "run", "--directory", "/app", "-m", "mcp_redmine.server", "main"]